/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DienstenRouteImport } from './routes/diensten'
import { Route as FotosRouteImport } from './routes/fotos'
import { Route as OverOnsRouteImport } from './routes/over-ons'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DienstenRoute = DienstenRouteImport.update({
  id: '/diensten',
  path: '/diensten',
  getParentRoute: () => rootRouteImport,
} as any)
const FotosRoute = FotosRouteImport.update({
  id: '/fotos',
  path: '/fotos',
  getParentRoute: () => rootRouteImport,
} as any)
const OverOnsRoute = OverOnsRouteImport.update({
  id: '/over-ons',
  path: '/over-ons',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/diensten': typeof DienstenRoute
  '/fotos': typeof FotosRoute
  '/over-ons': typeof OverOnsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/diensten': typeof DienstenRoute
  '/fotos': typeof FotosRoute
  '/over-ons': typeof OverOnsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/diensten': typeof DienstenRoute
  '/fotos': typeof FotosRoute
  '/over-ons': typeof OverOnsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/diensten' | '/fotos' | '/over-ons'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/diensten' | '/fotos' | '/over-ons'
  id: '__root__' | '/' | '/contact' | '/diensten' | '/fotos' | '/over-ons'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DienstenRoute: typeof DienstenRoute
  FotosRoute: typeof FotosRoute
  OverOnsRoute: typeof OverOnsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diensten': {
      id: '/diensten'
      path: '/diensten'
      fullPath: '/diensten'
      preLoaderRoute: typeof DienstenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotos': {
      id: '/fotos'
      path: '/fotos'
      fullPath: '/fotos'
      preLoaderRoute: typeof FotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-ons': {
      id: '/over-ons'
      path: '/over-ons'
      fullPath: '/over-ons'
      preLoaderRoute: typeof OverOnsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DienstenRoute: DienstenRoute,
  FotosRoute: FotosRoute,
  OverOnsRoute: OverOnsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
