name: Deploy Vite To GitHub Pages

on:
  push:
    branches: [ "main", "master" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --legacy-peer-deps --force

      - name: Build Website
        run: |
          npm run build -- --skipLibCheck || npx vite build
        env:
          CI: false

      - name: Determine Target Folder
        id: target
        run: |
          # Dit controleert of de website in dist of build staat, of direct in de root
          if [ -d "dist" ]; then
            echo "folder=./dist" >> $GITHUB_OUTPUT
          elif [ -d "build" ]; then
            echo "folder=./build" >> $GITHUB_OUTPUT
          else
            echo "folder=." >> $GITHUB_OUTPUT
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.target.outputs.folder }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
